#!/usr/bin/env python3
"""
make_tables.py — generate paper/tables/*.tex (booktabs FRAGMENTS).

Conventions:
- Each output contains ONLY the tabular environment (booktabs), no
  \\begin{table} / caption / label — the manuscript wraps it, so captions are
  editable without regenerating.
- Rounding is defined HERE once; the prose cites numbers via numbers.tex
  macros, never by retyping table cells.
- No statistics are computed here — pure CSV → LaTeX formatting.

Tables:
  tab1_descriptives.tex      Table 1 — descriptive anchors (panel A moments, B tails)
  tab2_qlp_main.tex          Table 2 — main QLP beta_shock, 6 tau x 6 h
  tab3_subsample.tex         Table 3 panel — subsample stability (beta + Delta/MDE)
  tab4_exceedance_skew_mde.tex Table 4 — bounded null (Delta, skew, MDE verdicts)
  tab5_size_ratio.tex        Table 5 — size ratios
  tab6_oos.tex               Table 6 — OOS pinball skill + DM p
  tabA1_block_sensitivity.tex  Appendix — MBB block-length sensitivity
  tabA2_se_ratio.tex           Appendix — same-spec kernel-vs-bootstrap SE ratio

Run
---
    .venv/bin/python scripts/paper/make_tables.py
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
sys.path.insert(0, str(ROOT))

from config import ECON_DIR  # noqa: E402

OUT_DIR = ROOT / "paper" / "tables"
H_TABLE = [0, 1, 3, 6, 12, 24]
TAUS = [0.01, 0.05, 0.10, 0.50, 0.90, 0.95]


def w(name: str, body: str) -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    path = OUT_DIR / name
    header = ("% GENERATED by scripts/paper/make_tables.py — DO NOT EDIT\n"
              "% fragment only: wrap in \\begin{table} + caption in the manuscript\n")
    path.write_text(header + body + "\n")
    print(f"  wrote {path}")


def f3(x):  # signed, 3 dp
    return f"{x:.3f}"


def f4(x):
    return f"{x:.4f}"


def f5(x):
    return f"{x:.5f}"


def pv(x):
    return "$<$0.001" if x < 0.001 else f"{x:.3f}"


# ────────────────────────────────────────────────────────────
def tab1_descriptives() -> None:
    de = pd.read_csv(ECON_DIR / "descriptive_stats.csv")

    def s(var, st):
        return float(de[(de.variable == var) & (de.statistic == st)].value.iloc[0])

    rows_a = [
        ("$N$ (hours)", f"{int(s('ret_eth_perp','N')):,}", f"{int(s('ret_btc_spot','N')):,}"),
        ("Mean", f4(s('ret_eth_perp', 'mean')), f4(s('ret_btc_spot', 'mean'))),
        ("Std.\\ dev.", f3(s('ret_eth_perp', 'std')), f3(s('ret_btc_spot', 'std'))),
        ("Skewness", f3(s('ret_eth_perp', 'skew')), f3(s('ret_btc_spot', 'skew'))),
        ("Excess kurtosis", f"{s('ret_eth_perp','excess_kurt'):.1f}", f"{s('ret_btc_spot','excess_kurt'):.1f}"),
        ("Min", f"{s('ret_eth_perp','min'):.2f}", f"{s('ret_btc_spot','min'):.2f}"),
        ("$p_{1}$", f"{s('ret_eth_perp','p1'):.2f}", f"{s('ret_btc_spot','p1'):.2f}"),
        ("$p_{99}$", f"{s('ret_eth_perp','p99'):.2f}", f"{s('ret_btc_spot','p99'):.2f}"),
        ("Max", f"{s('ret_eth_perp','max'):.2f}", f"{s('ret_btc_spot','max'):.2f}"),
    ]
    rows_b = [
        ("\\#\\{$r \\le -5\\%$\\} / \\#\\{$r \\ge +5\\%$\\}",
         f"{int(s('tail_asymmetry','n_below_minus5'))} / {int(s('tail_asymmetry','n_above_plus5'))}"),
        ("\\#\\{$r \\le -7\\%$\\} / \\#\\{$r \\ge +7\\%$\\}",
         f"{int(s('tail_asymmetry','n_below_minus7'))} / {int(s('tail_asymmetry','n_above_plus7'))}"),
        ("$|p_{1}|/p_{99}$ (quantile ratio)", f"{s('tail_asymmetry','q_ratio_p1_p99'):.2f}"),
        ("$P(\\text{liq}>0 \\mid \\text{worst 1\\% hours})$", f"{s('liq_crosstab','p_liq_worst1'):.1f}\\%"),
        ("$P(\\text{liq}>0 \\mid \\text{best 1\\% hours})$", f"{s('liq_crosstab','p_liq_best1'):.1f}\\%"),
        ("$P(\\text{liq}>0)$ (all hours)", f"{s('liq_crosstab','p_liq_all'):.1f}\\%"),
    ]
    body = "\\begin{tabular}{lcc}\n\\toprule\n"
    body += " & ETH perp & BTC spot \\\\\n\\midrule\n"
    body += "\\multicolumn{3}{l}{\\emph{Panel A: hourly log-returns (\\%)}} \\\\\n"
    for k, a, b in rows_a:
        body += f"{k} & {a} & {b} \\\\\n"
    body += "\\midrule\n\\multicolumn{3}{l}{\\emph{Panel B: tail asymmetry and liquidation co-occurrence (ETH)}} \\\\\n"
    for k, v in rows_b:
        body += f"{k} & \\multicolumn{{2}}{{c}}{{{v}}} \\\\\n"
    body += "\\bottomrule\n\\end{tabular}"
    w("tab1_descriptives.tex", body)


def tab2_qlp_main() -> None:
    qlp = pd.read_csv(ECON_DIR / "quantile_lp_results.csv")
    body = "\\begin{tabular}{l" + "c" * len(H_TABLE) + "}\n\\toprule\n"
    body += "$\\tau$ & " + " & ".join(f"$h={h}$" for h in H_TABLE) + " \\\\\n\\midrule\n"
    for tau in TAUS:
        cells = []
        for h in H_TABLE:
            r = qlp[(np.isclose(qlp.tau, tau)) & (qlp.h == h)]
            cells.append(f3(float(r.beta_shock.iloc[0])) if len(r) else "--")
        body += f"{tau:.2f} & " + " & ".join(cells) + " \\\\\n"
    body += "\\bottomrule\n\\end{tabular}"
    w("tab2_qlp_main.tex", body)


def tab3_subsample() -> None:
    sub = pd.read_csv(ECON_DIR / "subsample_stability.csv")
    names = [("full", "Full sample"), ("first_half", "First half"),
             ("second_half", "Second half"), ("loo_aug2024", "Excl.\\ Aug-2024")]
    hs = [0, 6, 12, 24]
    body = "\\begin{tabular}{l" + "c" * len(hs) + "cc}\n\\toprule\n"
    body += (" & \\multicolumn{" + str(len(hs)) + "}{c}{$\\beta_h(0.01)$} & "
             "\\multicolumn{2}{c}{$\\Delta$ at $h{=}12$} \\\\\n")
    body += ("\\cmidrule(lr){2-" + str(1 + len(hs)) + "}\\cmidrule(lr){" + str(2 + len(hs))
             + "-" + str(3 + len(hs)) + "}\n")
    body += ("Subsample & " + " & ".join(f"$h={h}$" for h in hs)
             + " & estimate & MDE$_{80}$ \\\\\n\\midrule\n")
    for key, label in names:
        b = sub[(sub.subsample == key) & (sub.object == "beta_q01")].set_index("h")
        d = sub[(sub.subsample == key) & (sub.object == "delta_exceed_a01")].set_index("h")
        cells = [f3(b.loc[h, "estimate"]) if h in b.index else "--" for h in hs]
        de = f5(d.loc[12, "estimate"]) if 12 in d.index else "--"
        dm = f5(d.loc[12, "mde80"]) if 12 in d.index else "--"
        body += f"{label} & " + " & ".join(cells) + f" & {de} & {dm} \\\\\n"
    body += "\\bottomrule\n\\end{tabular}"
    w("tab3_subsample.tex", body)


def tab4_exceedance_skew_mde() -> None:
    pe = pd.read_csv(ECON_DIR / "exceedance_paired.csv")
    sk = pd.read_csv(ECON_DIR / "skew_test.csv").set_index("measure")
    mde = pd.read_csv(ECON_DIR / "mde_equivalence.csv")

    body = "\\begin{tabular}{lcccc}\n\\toprule\n"
    body += ("\\multicolumn{5}{l}{\\emph{Panel A: paired exceedance asymmetry "
             "$\\Delta_h = \\beta^{\\text{down}}_h - \\beta^{\\text{up}}_h$, "
             "$\\alpha = 1\\%$ (per-period)}} \\\\\n")
    body += "$h$ & $\\Delta$ & 95\\% CI & & $p$ \\\\\n\\midrule\n"
    for h in H_TABLE:
        r = pe[(np.isclose(pe.alpha, 0.01)) & (pe.h == h)]
        if not len(r):
            continue
        r = r.iloc[0]
        body += (f"{h} & {f5(r.delta)} & [{f5(r.ci_lo)}, {f5(r.ci_hi)}] & & "
                 f"{pv(r.pval)} \\\\\n")
    body += "\\midrule\n\\multicolumn{5}{l}{\\emph{Panel B: vol-standardized skew tests (h=0)}} \\\\\n"
    body += "measure & $\\beta$ & 95\\% CI & & $p$ \\\\\n\\midrule\n"
    for m, label in (("skew_tail05", "tail indicator, $\\tau{=}5\\%$"),
                     ("skew_tail01", "tail indicator, $\\tau{=}1\\%$"),
                     ("z3_winsor", "winsorised $z^3$")):
        r = sk.loc[m]
        body += (f"{label} & {f5(r.beta)} & [{f5(r.ci_lo)}, {f5(r.ci_hi)}] & & "
                 f"{pv(r.pval)} \\\\\n")
    body += "\\midrule\n\\multicolumn{5}{l}{\\emph{Panel C: equivalence (TOST) verdicts vs.\\ SESOI spans}} \\\\\n"
    body += "object & MDE$_{80}$ & IQR span & strict span & $p_{10}{\\to}p_{90}$ \\\\\n\\midrule\n"

    def verdict(v):
        return {"EQUIVALENT-TO-NEGLIGIBLE": "equiv.", "INCONCLUSIVE": "inconcl.",
                "N/A-UNITS": "n/a"}.get(str(v), str(v).lower())

    for _, r in mde.iterrows():
        label = str(r.alpha_or_measure).replace("alpha=", "$\\alpha{=}$").replace("_", "\\_")
        obj = str(r.object).replace("_", "\\_")
        m80 = f5(r.mde_80) if np.isfinite(r.mde_80) else "--"
        v1, v2, v3 = (verdict(r.verdict_iqr), verdict(r.verdict_p50p95),
                      verdict(r.verdict_p10p90))
        body += f"{obj} ({label}) & {m80} & {v1} & {v2} & {v3} \\\\\n"
    body += "\\bottomrule\n\\end{tabular}"
    w("tab4_exceedance_skew_mde.tex", body)


def tab5_size_ratio() -> None:
    sz = pd.read_csv(ECON_DIR / "size_ratio.csv").set_index("metric")
    rows = [
        ("mean_daily_defi_liq_vs_daily_eth_spot_perp_turnover",
         "Mean daily DeFi liq.\\ / daily ETH turnover"),
        ("median_daily_defi_liq_vs_daily_eth_spot_perp_turnover",
         "Median daily DeFi liq.\\ / daily ETH turnover"),
        ("max_day_defi_liq_vs_daily_eth_spot_perp_turnover",
         "Worst day (2024-08-05) / daily ETH turnover"),
        ("worst_7d_defi_liq_vs_7d_eth_spot_perp_turnover",
         "Worst 7 days / 7-day ETH turnover"),
        ("max_day_defi_liq_vs_oct2025_cascade",
         "Worst day / Oct-2025 CEX-perp cascade ($\\sim$\\$19bn)"),
        ("total_sample_defi_liq_vs_oct2025_single_day_cascade",
         "Whole-sample total / Oct-2025 single-day cascade"),
    ]
    body = "\\begin{tabular}{lc}\n\\toprule\n & Share (\\%) \\\\\n\\midrule\n"
    for key, label in rows:
        v = float(sz.loc[key, "ratio_pct"])
        vs = f"{v:.4f}" if v < 0.01 else (f"{v:.2f}" if v < 10 else f"{v:.1f}")
        body += f"{label} & {vs} \\\\\n"
    body += "\\bottomrule\n\\end{tabular}"
    w("tab5_size_ratio.tex", body)


def tab6_oos() -> None:
    oos = pd.read_csv(ECON_DIR / "oos_predictive.csv")
    taus = [0.01, 0.05, 0.95, 0.99]
    hs = [1, 3, 6, 12, 24]
    body = "\\begin{tabular}{l" + "c" * len(hs) + "}\n\\toprule\n"
    body += " & " + " & ".join(f"$h={h}$" for h in hs) + " \\\\\n"
    for bench, label in (("qr_controls", "vs.\\ nested QR (no liquidation terms)"),
                         ("garch11", "vs.\\ GARCH(1,1) benchmark")):
        body += f"\\midrule\n\\multicolumn{{{1+len(hs)}}}{{l}}{{\\emph{{{label}}}}} \\\\\n"
        sub = oos[oos.benchmark == bench].set_index(["tau", "h"])
        for tau in taus:
            cells = []
            for h in hs:
                r = sub.loc[(tau, h)]
                stars = ("$^{***}$" if r.dm_pval < 0.01 else
                         "$^{**}$" if r.dm_pval < 0.05 else
                         "$^{*}$" if r.dm_pval < 0.10 else "")
                cells.append(f"{100 * r.skill:.2f}{stars}")
            body += f"$\\tau={tau:.2f}$ & " + " & ".join(cells) + " \\\\\n"
    body += "\\bottomrule\n\\end{tabular}"
    w("tab6_oos.tex", body)


def tabA1_block_sensitivity() -> None:
    bl = pd.read_csv(ECON_DIR / "block_sensitivity.csv")
    d = bl[bl.object == "delta_paired"].set_index(["h", "block_size"])
    blocks = [12, 24, 36, 48]
    hs = sorted({h for h, _ in d.index})
    body = "\\begin{tabular}{l" + "c" * len(blocks) + "}\n\\toprule\n"
    body += ("$h$ & " + " & ".join(f"block $={b}$h" for b in blocks)
             + " \\\\\n\\midrule\n")
    for h in hs:
        cells = []
        for b in blocks:
            r = d.loc[(h, b)]
            cells.append(f"{f5(r.mde80)}")
        body += f"{h} & " + " & ".join(cells) + " \\\\\n"
    body += "\\bottomrule\n\\end{tabular}"
    w("tabA1_block_sensitivity.tex", body)


def tabA2_se_ratio() -> None:
    se = pd.read_csv(ECON_DIR / "se_ratio_nb07.csv")
    body = "\\begin{tabular}{lccc}\n\\toprule\n"
    body += "$h$ & kernel SE & bootstrap SE & ratio \\\\\n\\midrule\n"
    for _, r in se.iterrows():
        body += (f"{int(r.h)} & {f4(r.se_kernel)} & {f4(r.se_boot_M)} & "
                 f"{r.ratio:.2f} \\\\\n")
    body += "\\bottomrule\n\\end{tabular}"
    w("tabA2_se_ratio.tex", body)


def main() -> int:
    for fn in (tab1_descriptives, tab2_qlp_main, tab3_subsample,
               tab4_exceedance_skew_mde, tab5_size_ratio, tab6_oos,
               tabA1_block_sensitivity, tabA2_se_ratio):
        fn()
    print("Done — 8 fragments in paper/tables/")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
